title: Bugxyb
author: Bugxyb
description: 随心所欲

markdown: kramdown
highlighter: rouge
permalink: /:title

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

url:
baseurl:

# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
